import Feed from '@/components/Feed';
import Header from '@/components/Header'
import Menubar from '@/components/Menubar';
import SideBar from '@/components/SideBar';
import Head from 'next/head'


export default function Home() {

  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className="flex ">
        <SideBar />
        <Feed/>
        <Menubar/>
      </main>
    </div>
  )
}

