import Feed from '@/components/Feed';
import Header from '@/components/Header'
import Login from '@/components/Login';
import Menubar from '@/components/Menubar';
import SideBar from '@/components/SideBar';
import Head from 'next/head'


export default function Home({ session }) {
  // if (!session) return <Login />;
  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className="flex ">
        <SideBar />
        <Feed/>
        <Menubar/>
      </main>
    </div>
  )
}

// export async function getServerSideProps(context) {
//   // Get User
//   const session = await getSession(context);

//   const posts = await db.collection("posts").orderBy("timestamp", "desc").get();

//   const docs = posts.docs.map((post) => ({
//     id: post.id,
//     ...post.data(),
//     timestamp: null,
//   }));

//   return {
//     props: { session, posts: docs },
//   };
// }